export const metadata = {
    title: "iBlog-About",
    description: "Generated by create next app",
  };
export default function page(){
    return(
        <>
        This is about
        </>
    )
}